# Generated by Django 4.0.3 on 2022-05-03 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0002_alter_group_user_alter_post_imageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='facebook.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to='facebook.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.BooleanField(null=True),
        ),
    ]
