# Generated by Django 4.0.3 on 2022-05-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_remove_post_likes_group_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to='facebook.profile'),
        ),
    ]
