# Generated by Django 4.0.3 on 2022-05-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
