# Generated by Django 4.0.3 on 2022-05-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_alter_post_imageurl_alter_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='facebook.profile'),
        ),
    ]
