# Generated by Django 4.0.3 on 2022-05-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0012_alter_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
