# Generated by Django 4.0.3 on 2022-05-31 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0015_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imageUrl',
            field=models.CharField(blank=True, default='https://www.attendit.net/images/easyblog_shared/July_2018/7-4-18/totw_network_profile_400.jpg', max_length=400, null=True),
        ),
    ]
