# Generated by Django 4.0.3 on 2022-05-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0016_alter_post_user_alter_profile_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imageUrl',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
