# Generated by Django 4.0.3 on 2022-05-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0017_alter_profile_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='imageUrl',
        ),
    ]
